
[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.14.1"

[[constraint]]
  name = "github.com/stackimpact/stackimpact-go"
  version = "2.3.9"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.6"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"
